export interface FillterAgg {
  contrast: number,
  brightness: number,
  redMultiplier: number,
  greenMultiplier: number,
  blueMultiplier: number,
  saturation: number, 
  hue: number,
  // saturation: number,
  // hue: number,
  // blur: number,
  // sharpen: number,
  // noise: number,
  // pixelate: number,
  // gamma: number,
  // invert: number,
}
